version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: example_app/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: "redis:alpine"

  db:
    image: "postgres:13"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

